name: Build
on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Post diff
      run: |
          curl --url https://i9kin.avevad.com/pull/9kin/conspects/${{ github.event.pull_request.number }}?hash=${{ secrets.cihash }} 
